# Generated by Django 3.2.17 on 2023-02-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('product', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='program',
            field=models.ForeignKey(db_column='program', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_program', to='program.program'),
        )
    ]
