# Generated by Django 3.2.17 on 2023-02-24 12:37
import logging

from django.db import migrations, models
from product.models import Product

logger = logging.getLogger(__name__)


def insert_treatment_ceiling_type(apps):
    products = Product.objects.all().filter(
        validity_to__isnull=True,
        ceiling_type__isnull=True,
        ded_op_treatment__isnull=False,
        ded_ip_treatment__isnull=False,
        ded_treatment__isnull=False,
        max_treatment__isnull=False,
        max_ip_treatment__isnull=False,
        max_op_treatment__isnull=False
    )
    insert_values(apps, products, "ceiling_type", "T")


def insert_policy_ceiling_type(apps):
    products = Product.objects.all().filter(
        validity_to__isnull=True,
        ceiling_type__isnull=True,
        ded_op_policy__isnull=False,
        ded_ip_policy__isnull=False,
        ded_policy__isnull=False,
        max_policy__isnull=False,
        max_ip_policy__isnull=False,
        max_op_policy__isnull=False
    )
    insert_values(apps, products, "ceiling_type", "P")


def insert_insuree_ceiling_type(apps):
    products = Product.objects.all().filter(
        validity_to__isnull=True,
        ceiling_type__isnull=True
    )
    insert_values(apps, products, "ceiling_type", "I")


def insert_values(apps, list_of_objects: list, field: str, value: str):
    Program = apps.get_model('program', 'Program')
    # Get or create a default program
    default_program = Program.objects.first()
    if not default_program:
        default_program = Program.objects.create(code="DEFAULT", nameProgram="Default Program")
    for single_object in list_of_objects:
        setattr(single_object, field, value)
        if not single_object.program_id:
            single_object.program = default_program
        single_object.save()


def insert_ceiling_types(apps, schema_editor):
    """
    Insert ceiling types based on ded/max values.
    Default value is set to "Insuree"
    """
    insert_treatment_ceiling_type(apps)
    insert_policy_ceiling_type(apps)
    insert_insuree_ceiling_type(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20231219_1939'),
    ]

    operations = [
        migrations.RunPython(insert_ceiling_types, migrations.RunPython.noop),
    ]
